title: My Trips & Adventures
description: Travel itineraries and trip planning
author: You
baseurl: "/homework"
url: "https://madathil22.github.io"

# Jekyll settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
